version: '3'
services:
  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
      - ./web1/nginx.conf:/etc/nginx/conf.d/default.conf
  web2:
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
  gateway:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./gateway/certs:/certs
    links:
      - web1
      - web2



