version: '3'
services:
  web1:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
    - ./staticserve:/usr/share/nginx/html
  web2:
    image: nginx:alpine
    ports:
    - "8081:80"
    volumes:
    - ./staticserve:/usr/share/nginx/html
